Feature/arrays
igor-arkhipov/study pull request #1
Opened 2021-11-17 23:45 UTC by igor-arkhipov

2021-11-18 15:12 UTC, moklidia requested changes

2021-11-18 15:12 UTC, moklidia commented on test/exercise/arrays/solution.rb
> +          max_arrvalue = elem if elem > max_arrvalue
max_arrvalue - это не очень хорошее название переменной

2021-11-18 15:12 UTC, moklidia commented on test/exercise/arrays/solution.rb
> +        array_end = array_border_end || array.length - 1
Ты мог бы сразу прописать это дефолтными значениями аргументов в сигнатуре функции

2021-11-18 16:51 UTC, igor-arkhipov commented on test/exercise/arrays/solution.rb
> +        array_end = array_border_end || array.length - 1
речь же про array_border_begin ?

2021-11-18 16:54 UTC, igor-arkhipov commented on test/exercise/arrays/solution.rb
> +          max_arrvalue = elem if elem > max_arrvalue
поменял, но по мне − чуть больше контекста в переменной даже хорошо. 
или snake_case имелся ввиду?

2021-11-19 11:29 UTC, moklidia approved these changes

2021-11-21 10:58 UTC, merged